# Generated by Django 4.2.5 on 2023-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthcheck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicebeatmodel",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicebeatmodel",
            name="device_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="devicebeatmodel",
            name="used_passphrase",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
