# Generated by Django 4.2.5 on 2024-04-06 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "No Rush"),
                            (2, "Need this tomorrow"),
                            (3, "Need this in a few hours"),
                            (4, "Need this in hour"),
                            (5, "ASAP"),
                        ]
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("delivery_location", models.CharField(max_length=255)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("file_to_print", models.FileField(upload_to="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
