# Generated by Django 4.2.5 on 2024-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printingserver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeddocument",
            name="number_of_pages",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
