# Generated by Django 4.2.5 on 2024-04-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpermonitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helperdutytimemodel",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
