# Generated by Django 4.2.5 on 2023-10-11 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticScreenSwitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('change_time_seconds', models.IntegerField(default=60)),
                ('randomise', models.BooleanField(default=False)),
                ('last_switch', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('current_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='current_screen_command', to='screen.automaticcommand')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=255)),
                ('base_command', models.CharField(max_length=255)),
                ('args', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='screen.screencommand')),
                ('switching_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='switching_screens_group', to='screen.automaticscreenswitcher')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passphrase', models.CharField(max_length=255)),
                ('last_connected_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('overriden_current_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='screen.screencommand')),
                ('screen_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='screen.screengroup')),
            ],
        ),
        migrations.AddField(
            model_name='automaticcommand',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='screen.screencommand'),
        ),
        migrations.AddField(
            model_name='automaticcommand',
            name='screen_switcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='automatic_commands', to='screen.automaticscreenswitcher'),
        ),
        migrations.AlterUniqueTogether(
            name='automaticcommand',
            unique_together={('screen_switcher', 'number_order')},
        ),
    ]
