# Generated by Django 4.2.5 on 2023-11-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automaticcommand",
            options={"ordering": ["created"]},
        ),
        migrations.AlterUniqueTogether(
            name="automaticcommand",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="automaticcommand",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="force_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screengroup",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="automaticcommand",
            name="number_order",
        ),
    ]
