# Generated by Django 4.2.5 on 2023-11-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automaticcommand",
            options={"ordering": ["created"]},
        ),
        migrations.AlterUniqueTogether(
            name="automaticcommand",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="automaticcommand",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="background_audio_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="force_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screencommand",
            name="permit_background_audio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screengroup",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="automaticcommand",
            name="number_order",
        ),
    ]
