# Generated by Django 4.2.5 on 2024-04-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("screen", "0002_alter_automaticcommand_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("remote_timestamp", models.DateTimeField()),
                ("ip_addresses", models.JSONField(blank=True, null=True)),
                ("zerotier_status", models.JSONField(blank=True, null=True)),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="screen.screen"
                    ),
                ),
            ],
        ),
    ]
